apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poll
  template:
    metadata:
      labels:
        app: poll
    spec:
      containers:
      - name: poll
        image: epitechcontent/t-dop-600-poll:k8s
        resources:
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: redis-config
        - secretRef:
            name: postgres-secret
        - configMapRef:
            name: postgres-config
